# Generated by Django 5.0.6 on 2024-06-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Blog',
        ),
    ]
